/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5dcc4fd7f1ef4518a5383351
*
* You will get 10% discount for each one of your friends
* 
*/
import React, { Component } from "react";
import { StyleSheet } from "react-native";
import {
  Header,
  Title,
  Container,
  Content,
  Body,
  Button,
  Text,
  Icon,
  Right,
  Left,
  Form,
  ListItem,
  Item,
  Label,
  Input,
  Picker,
} from "native-base";
import SecurityService from "../security/SecurityService";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Custom Actions


// START IMPORT ACTIONS
import ProductActions from "../redux/actions/ProductActions";
import OrderActions from "../redux/actions/OrderActions";

// END IMPORT ACTIONS

/** APIs

* actionsProduct.create
*	@description CRUD ACTION create
*
* actionsProduct.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsOrder.list
*	@description CRUD ACTION list
*
* actionsProduct.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*

**/


class ProductEdit extends Component {
  
  // Init product
  constructor(props) {
    super(props);
    this.state = {
      product: {},
      authorized: false
    };
  }

  // Load data on start
  componentWillMount() {

    this.props.navigation.addListener("willFocus", async () => { 
      // Check security
      if (await SecurityService.isAuth([  ])) {
        this.setState({ authorized: true });
      } else {
        this.props.navigation.navigate("Login", {
          showError: "Not authorized"
        });
        return;
      }


      // Load data
      const itemId = this.props.navigation.getParam("id", "new");
      if (itemId !== "new") {
        this.props.actionsProduct.loadProduct(itemId);
      } else {
        this.setState({
          product: {}
        });
      }
      
      this.props.actionsOrder.loadOrderList();
    });
  }

  // Clear reducer
  componentWillUnmount() {
    this.setState({
      product: {}
    });
    this.props.actionsProduct.reset();
  }

  // Insert props product in state
  componentWillReceiveProps(props) {
    this.setState({
      product: props.product
    });
  }

  // Save data
  save() {
    // Validation
    let errors = {};
    
    if (!this.state.product.Price || this.state.product.Price.trim() === "") {
      errors.Price = true;
    }
    
    if (!this.state.product.Type || this.state.product.Type.trim() === "") {
      errors.Type = true;
    }
    

    this.setState({ errors: errors });
    if (Object.keys(errors).length > 0) {
      return;
    }

    // Save
    if (this.state.product._id) {
      // Edit
      this.props.actionsProduct.saveProduct(this.state.product).then(data => {
        this.props.navigation.navigate("ProductList");
      });
    } else {
      // Create
      this.props.actionsProduct.createProduct(this.state.product).then(data => {
        this.props.navigation.navigate("ProductList");
      });
    }
  }

  // Show content
  render() { 

    // Check security
    if (!this.state.authorized) {
      return null;
    }

    return (
      <Container>
        <Header>
          <Left>
            <Button
            transparent
            onPress={() => this.props.navigation.goBack()}
            >
              <Icon name="arrow-back" />
            </Button>
          </Left>
          <Body>
            <Title>Detail Product</Title>
          </Body>
          <Right>
            <Button transparent onPress={() => this.save()}>
              <Text>Save</Text>
            </Button>
          </Right>
        </Header>
        <Content>
          <Form>
            
            <Item floatingLabel {...(this.state.errors && this.state.errors.Price === true ? { style: styles.validatorItem } : {})}>
              <Label
                {...(this.state.errors && this.state.errors.Price === true ? { style: styles.validatorLabel } : {})}>
                Price *
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.product, { Price: value }))
                }
                value={this.state.product.Price && this.state.product.Price.toString()}
              />
            </Item>
            {this.state.errors && this.state.errors.Price === true && (
              <Text style={styles.validatorMessage}>Value is required</Text>
            )}
          
            
            <Item floatingLabel {...(this.state.errors && this.state.errors.Type === true ? { style: styles.validatorItem } : {})}>
              <Label
                {...(this.state.errors && this.state.errors.Type === true ? { style: styles.validatorLabel } : {})}>
                Type *
              </Label>
              <Input
                onChangeText={value =>
                  this.setState(Object.assign(this.state.product, { Type: value }))
                }
                value={this.state.product.Type && this.state.product.Type.toString()}
              />
            </Item>
            {this.state.errors && this.state.errors.Type === true && (
              <Text style={styles.validatorMessage}>Value is required</Text>
            )}
          

          {/* RELATIONS */}
          
          {/* Relation 1:m has with Order */}
          
          <Item stackedLabel>
            <Label >
              Has
            </Label>
            <Picker
              mode="dropdown"
              iosHeader="Select a value"
              iosIcon={<Icon name="arrow-down" />}
              style={{ width: undefined }}
              selectedValue={this.state.product.has }
              value={this.state.product.has }
              onValueChange={value =>
                this.setState(Object.assign(this.state.product, { has: value }))
              }
            >
              {this.props.listOrder &&
                this.props.listOrder.map(row => (
                  <Picker.Item label={row._id} value={row._id} key={row._id}>
                    {row._id}
                  </Picker.Item>
                ))}
            </Picker>
          </Item>
          
          

          </Form>
        </Content>
      </Container>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsProduct: bindActionCreators(ProductActions, dispatch),
    actionsOrder: bindActionCreators(OrderActions, dispatch),
  };
};

// Validate types
ProductEdit.propTypes = { 
  actionsProduct: PropTypes.object.isRequired,
  actionsOrder: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    product: state.ProductEditReducer.product,
    listOrder: state.ProductEditReducer.listOrder
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(ProductEdit);

const styles = StyleSheet.create({
  validatorItem: { borderColor: "red" },
  validatorLabel: { color: "red" },
  validatorMessage: { color: "red", marginLeft: 15, marginTop: 5 }
});
